### ISSUE TITLE
Delivery acknowledgements can time out on long tasks

### ISSUE THREAD

**Issue by spenczar** [B612-Asteroid-Institute/thorctl#4]
Spotted by @KatKiker:

```
14:19:08.750 [INFO] thor - marking task 4 as a success
14:19:19.823 [ERROR] thor - task 4 failed
Traceback (most recent call last):
  File "/Users/kathleenkiker/Spencer_work/spence_latest/thor/thor/taskqueue/client.py", line 378, in handle_task
    self.mark_task_succeeded(task, bucket, out_dir)
  File "/Users/kathleenkiker/Spencer_work/spence_latest/thor/thor/taskqueue/client.py", line 414, in mark_task_succeeded
    self.queue.channel.basic_ack(delivery_tag=task._delivery_tag)
  File "/Users/kathleenkiker/anaconda3/envs/sp-1.2/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2112, in basic_ack
    self._flush_output()
  File "/Users/kathleenkiker/anaconda3/envs/sp-1.2/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1339, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more')
14:19:19.829 [ERROR] thor - marking task 4 as a failure, reason: (406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more')
```

Here we have a task that had succeeded - but when we went to call `channel.basic_ack` we got a `PRECODINITION_FAILED` response because the task had timed out after 1800000ms, which is 30 minutes.

As the error message says, there's a way to configure this timeout, which we should do.

**Comment by spenczar** [comment]
We updated the broker configuration file (in /etc/rabbitmq) so this is resolved.
