### ISSUE TITLE
`autoscale` command line argument returns socket error

### ISSUE THREAD

**Issue by moeyensj** [B612-Asteroid-Institute/thorctl#43]
When trying to manually trigger an autoscale on production-tasks, the following error gets thrown:

```
thorctl autoscale production-tasks
Traceback (most recent call last):
  File "/home/moeyensj/software/anaconda3/envs/thorctl_py39/bin/thorctl", line 33, in <module>
    sys.exit(load_entry_point('thorctl', 'console_scripts', 'thorctl')())
  File "/home/moeyensj/repos/cloned/thorctl/thorcontrol/bin/thorctl/main.py", line 23, in main
    commands.dispatch(parser, args)
  File "/home/moeyensj/repos/cloned/thorctl/thorcontrol/bin/thorctl/commands.py", line 36, in dispatch
    autoscale(
  File "/home/moeyensj/repos/cloned/thorctl/thorcontrol/bin/thorctl/commands.py", line 336, in autoscale
    scaler = Autoscaler(rabbit_params, queues, max_size, machine_type)
  File "/home/moeyensj/repos/cloned/thorctl/thorcontrol/bin/thorctl/autoscaler.py", line 26, in __init__
    q_conn.connect()
  File "/home/moeyensj/repos/cloned/thorctl/thorcontrol/taskqueue/queue.py", line 54, in connect
    self.connection = pika.BlockingConnection(self.connection_params)
  File "/home/moeyensj/software/anaconda3/envs/thorctl_py39/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/moeyensj/software/anaconda3/envs/thorctl_py39/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/home/moeyensj/software/anaconda3/envs/thorctl_py39/lib/python3.9/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
  File "/home/moeyensj/software/anaconda3/envs/thorctl_py39/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

However, if I manually add workers via: 
```thorctl scale-up production-tasks --n-workers 10
12:28:12.604 [INFO] thorctl - production-tasks has 0 workers, scaling up to 10
12:28:12.604 [INFO] thorctl - creating worker production-tasks-worker-qzxfge in us-west1-a
12:28:14.978 [INFO] thorctl - creating worker production-tasks-worker-rxyqll in us-west1-b
12:28:16.960 [INFO] thorctl - creating worker production-tasks-worker-sbopuy in us-west1-c
12:28:19.276 [INFO] thorctl - creating worker production-tasks-worker-xhatdp in us-west1-a
12:28:21.578 [INFO] thorctl - creating worker production-tasks-worker-mqiqzy in us-west1-b
12:28:23.401 [INFO] thorctl - creating worker production-tasks-worker-ffmzta in us-west1-c
12:28:25.695 [INFO] thorctl - creating worker production-tasks-worker-pmjidc in us-west1-a
12:28:28.197 [INFO] thorctl - creating worker production-tasks-worker-nadpif in us-west1-b
12:28:30.165 [INFO] thorctl - creating worker production-tasks-worker-bhyyqz in us-west1-c
12:28:32.514 [INFO] thorctl - creating worker production-tasks-worker-yhfqen in us-west1-a
12:28:34.598 [INFO] thorctl - waiting for insert operation to complete
12:28:34.696 [INFO] thorctl - waiting for insert operation to complete
12:28:34.786 [INFO] thorctl - waiting for insert operation to complete
12:28:34.884 [INFO] thorctl - waiting for insert operation to complete
12:28:34.983 [INFO] thorctl - waiting for insert operation to complete
12:28:35.067 [INFO] thorctl - waiting for insert operation to complete
12:28:35.155 [INFO] thorctl - waiting for insert operation to complete
12:28:35.234 [INFO] thorctl - waiting for insert operation to complete
12:28:38.384 [INFO] thorctl - waiting for insert operation to complete
12:28:39.916 [INFO] thorctl - waiting for insert operation to complete
```
Then it works successfully.

**Comment by spenczar** [comment]
This bug is caused by not providing `thorctl` with a rabbit hostname to connect to. The socket error is _really_ that thorctl is attempting to connect to the default rabbit address, which is only reachable from within our google cloud project's network. 

This could be improved with better error messaging.
